######################################################################
# Automatically generated by qmake (3.0) Wed Aug 20 11:49:54 2014
######################################################################

TEMPLATE = app
TARGET = mrgui
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += hexspinbox.h window.h avr.h
SOURCES += hexspinbox.cpp main.cpp window.cpp avr.cpp
